[package]
name = "parque-oxidado"
version = "0.1.0"
authors = ["Lucho <sportelliluciano@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.2"
std-semaphore = "0.1.0"